set -g @minimal-tmux-fg "#000000"
set -g @minimal-tmux-bg "cyan"
set -g @minimal-tmux-justify "left"
set -g @minimal-tmux-indicator-str "#S"
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "bottom"

# Enables or disables the left and right status bar
set -g @minimal-tmux-right true
set -g @minimal-tmux-left true

# To add or remove extra text in status bar
set -g @minimal-tmux-status-right-extra ""
set -g @minimal-tmux-status-left-extra "  "

# To make the selection box rounded () or edged <>
set -g @minimal-tmux-use-arrow false
# set -g @minimal-tmux-right-arrow ""
# set -g @minimal-tmux-left-arrow ""

set -g @minimal-tmux-status-right "#H"

set -g status-right-length 20
set -g status-left-length 20
